import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Cloud Shorts <a href="/.">AWS APP Runner!</a>
        </h1>

        <p className={styles.description}>
          Working with <code className={styles.code}>AWS APP Runner</code>
        </p>
      </main>
    </div>
  );
}
